[package]
name = "puppeteer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["wayland"] }
bevy-inspector-egui = "0.28.0"
avian3d = { version = "0.2" }

[dev-dependencies]
bevy = { version = "0.15" }
