[package]
name = "puppeteer"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy-inspector-egui = "0.29"
avian3d = { version = "0.2.0" }

[dev-dependencies]
bevy = { version = "0.15", features = ["wayland"] }
