[package]
name = "bevy_z_character_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version= "0.13.2", features = ["wayland"]}
bevy-inspector-egui = "0.24.0"
bevy_xpbd_3d = {version= "0.4.2"}

[dev-dependencies]
bevy = {version= "0.13.2"}
