[package]
name = "puppeteer"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
bevy = { version = "0.16", default-features = false }
avian3d = "0.3"

[dev-dependencies]
bevy = { version = "0.16", features = ["wayland"] }
bevy-inspector-egui = "0.31"
